# Generated by Django 5.2.5 on 2025-08-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_article_contenu_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_modification',
        ),
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='CommandeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commandes/')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.commande')),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
