# Generated by Django 5.2.4 on 2025-08-17 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_commande_adresse_commande_nom_commande_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='article',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='main.commande')),
            ],
        ),
    ]
