# Generated by Django 5.2.4 on 2025-08-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_commande_article_remove_commande_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecommande',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
    ]
