# Generated by Django 5.2.4 on 2025-08-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_lignecommande_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='taille',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
