# Generated by Django 5.2.4 on 2025-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='couleur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
