# Generated by Django 5.2.4 on 2025-09-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_commande_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
