# Generated by Django 5.2.4 on 2025-09-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_commande_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix',
        ),
    ]
