# Generated by Django 5.2.4 on 2025-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_article_image_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_livraison',
            field=models.CharField(choices=[('domicile', 'Livraison à domicile'), ('retrait', 'Point de retrait')], default='domicile', max_length=20),
        ),
    ]
