# Generated by Django 5.2.4 on 2025-09-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_commande_commune_commande_type_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('Nouveau', '🆕 Nouveau'), ('Assuré', '✅ Assuré')], default='Nouveau', max_length=20),
        ),
    ]
